name: release-stub

# Controls when the action will run.
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "Building release tag, ${GITHUB_REF}"

      - name: Set TAG_VERSION
        run: echo "TAG_VERSION=$(echo ${GITHUB_REF#refs/tags/v})" >> $GITHUB_ENV

      - name: Get version from package.json
        id: package_version
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'package.json'
          prop_path: 'version'

      - name: make sure github tag matches package version
        if: ${{ env.TAG_VERSION != steps.package_version.outputs.prop }}
        run: |
          echo "Tag version, ${{ env.TAG_VERSION }}, does not match package.json version, ${{ env.PACKAGE_VERSION }}"  
          exit 1
        env:
          PACKAGE_VERSION: ${{ steps.package_version.outputs.prop }}

      - name: Create .npmignore before publishing package
        run: | 
          echo ".github" >> .npmignore 
          echo ".scannerwork" >> .npmignore
          echo "artifacts" >> .npmignore
          cat .npmignore 
