name: test-workflow

# Controls when the action will run.
on:
  push:

jobs:
  # This workflow contains a single job called "build"
  build:
    env: 
      VAR_A: true
      VAR_B: false

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "Building release tag, ${GITHUB_REF}"
 
      - name: Test if VAR_A is true
        if: ${{ env.VAR_A == 'true' }}
        run: echo "VAR_A is true"
     
      - name: Test if VAR_B is false
        if: ${{ env.env.VAR_B == 'false' }}
        run: echo "VAR_B is true. But should be false"
     
        

